name: C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Installation de CMake et du compilateur
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        sudo apt-get install -y gcc-12 g++-12
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100
        
    - name: Verify CMake version
      run: cmake --version
        
    - name: Build le repertoire
      run: mkdir build

    - name: Configurer CMake
      working-directory: ./build
      run: cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build le Project
      working-directory: ./build
      run: cmake --build . --config Release

    - name: List Build Directory
      working-directory: ./build
      run: ls -la

    - name:  Execution
      working-directory: ./build
      run: ./Tp_note_bellahsene || true
